M48
; DRILL file {KiCad (6.0.1)} date Mon Feb  7 23:09:00 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-02-07T23:09:00-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1100
%
G90
G05
T1
X1.895Y-4.095
X1.905Y-2.685
X1.905Y-3.39
X6.54Y-5.03
X6.55Y-3.43
T0
M30
